name: ci.yml
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    permissions: write-all

    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Setup PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, ctype, fileinfo, json, tokenizer, xml, pdo, pdo_mysql, openssl, curl, zip, imagick, swoole, pcntl
      - name: Cache Composer Dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 'latest'
      - name: Copy .ENV
        run: |
          cp .env.example .env
      - name: Install Composer Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress
      - name: Download Node Dependencies
        run: npm ci
      - name: Compile Assets
        run: npm run build
      - name: Generate App Key
        run: |
          php artisan key:generate
      - name: Package
        run: zip -r biblia-anotada.zip app/ bootstrap/ config/ database/ licenses/ node_modules/ public/ resources/ routes/ storage/ vendor/ .editorconfig .env.example .env .gitattributes .gitignore .prettierrc.yml artisan composer.json composer.lock docker-compose.yml LICENSE package-lock.json package.json phpunit.xml README.md tsconfig.json vite.config.js
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          path: ./biblia-anotada.zip
          name: biblia-anotada.zip

  create-release:
    permissions:
      contents: write

    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/download-artifact@v5.0.0
        with:
          name: biblia-anotada.zip
      - name: Calculate Checksum
        run: sha256sum biblia-anotada.zip > SHA256SUM
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: 'Dupla: Douglas Eduardo; Heber Ferreira Barra. Para rodar baixe o arquivo biblia-anotada.zip, extraia o arquivo, rode as migrations, etc.. Utilize o comando `composer run dev` para rodar o programa.'
          files: |
            SHA256SUM
            biblia-anotada.zip
          make_latest: true
